### ISSUE TITLE
Only allow instructors and admin groups to view username of anonymous posts

### ISSUE THREAD

**Issue by rosyyang224** [CMU-313/nodebb-f24-team-team#20]
Estimated effort: L t-shirt size
Dependencies among tasks: task #15 
Milestone: Sprint 2
Acceptance criteria: instructors and administrators can view the username of the anonymous post when the post is uploaded

**Comment by margarethe913** [comment]
Effort required for this task is too high, so we have reallocated hours to a different task.

**Comment by margarethe913** [comment]
Effort required for this task is too high, so we have reallocated hours to a different task.
